<a href="https://colab.research.google.com/github/NikhithaVarma/Guvi-Task/blob/main/DW21Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import the numpy package under the name np
import numpy as np

In [ ]:
#Print the numpy version and the configuration 
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [ ]:
#Create a null vector of size 10
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#How to find the memory size of any array 

print("%d bytes" % (Z.size * Z.itemsize))

80 bytes


In [ ]:
#How to get the documentation of the numpy add function from the command line? 
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
#Create a null vector of size 10 but the fifth value which is 1
Z= np.zeros(10)
Z[4]= 1
print (Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Create a vector with values ranging from 10 to 49
Z=np.arange(10,50)
print (Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Reverse a vector (first element becomes last)
Z= Z[::-1]
print (Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print (Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
#Create a 3x3 identity matrix 
Z= np.eye(3)
print (Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a 3x3x3 array with random values 
Z = np.random.random((3,3,3))
print (Z)

[[[0.18338101 0.54757626 0.95657848]
  [0.64446245 0.24658085 0.94056443]
  [0.88353667 0.01201943 0.30740905]]

 [[0.19227042 0.87953672 0.41233709]
  [0.66297183 0.94373722 0.13871989]
  [0.16861779 0.58292566 0.38465728]]

 [[0.05714398 0.20683535 0.6060468 ]
  [0.711488   0.30936171 0.33414866]
  [0.54233764 0.26402076 0.1784624 ]]]


In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.02468577538355421 0.9839476733365545


In [ ]:
#Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
print(Z)
m = Z.mean()
print ("Mean:", m)


[0.52111482 0.26623811 0.61187165 0.99885133 0.8355419  0.73639868
 0.74425056 0.30797666 0.44617084 0.11725321 0.13771203 0.82539769
 0.39322108 0.05788539 0.13545188 0.22533797 0.87460102 0.39461476
 0.98405022 0.11266903 0.23926487 0.69149334 0.82993587 0.17232025
 0.90341749 0.659701   0.18503608 0.41037698 0.09242713 0.57159689]
Mean: 0.4827392904785505


In [ ]:
#Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#How to add a border (filled with 0's) around an existing array?
Z = np.ones((3,3))
print(Z)
print()
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)



nan
False
False
nan
False


In [ ]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print (np.unravel_index(100, (6,7,8)))


(1, 5, 4)


In [ ]:
#Create a checkerboard 8x8 matrix using the tile function 
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Normalize a 5x5 random matrix 
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.         0.95414048 0.87111733 0.87116648 0.27309129]
 [0.8119451  0.04143666 0.87282291 0.88435925 0.1562148 ]
 [0.44475553 0.41914329 0.06555916 0.77611717 0.28368745]
 [0.03010086 0.42378937 0.6086395  0.60938155 0.08676182]
 [0.02491282 0.19280627 0.33542087 0.20965119 1.        ]]


In [ ]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [ ]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(10)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [ ]:
#What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#Consider an integer vector Z, which of these expressions are legal?
#Z**Z  
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7.,  8.,  9.])

In [ ]:
#What are the result of the following expressions
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-2. -6. -6.  1. -8. -3. -7.  8.  5. -6.]


In [ ]:
#How to find common values between two arrays? 
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 3 6 7]


In [ ]:
#How to ignore all numpy warnings (not recommended)
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [ ]:
#Is the following expressions true
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [ ]:
#How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-08-16
2022-08-17
2022-08-18


In [ ]:
#How to get all the dates corresponding to the month of July 2016
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#How to compute ((A+B)*(-A/2)) in place (without copy)
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
#Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[7. 2. 5. 3. 3. 7. 8. 2. 8. 7.]
[7. 2. 5. 3. 3. 7. 8. 2. 8. 7.]
[7. 2. 5. 3. 3. 7. 8. 2. 8. 7.]
[7 2 5 3 3 7 8 2 8 7]
[7. 2. 5. 3. 3. 7. 8. 2. 8. 7.]


In [ ]:
#Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded 
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#Create a random vector of size 10 and sort it
Z = np.random.random(10)
Z.sort()
print(Z)

[0.12109018 0.13104567 0.14225018 0.22457892 0.27433829 0.28670575
 0.31898005 0.55077204 0.78961108 0.8914174 ]


In [ ]:
#How to sum a small array faster than np.sum? 
Z = np.arange(10)
np.add.reduce(Z)

45

In [ ]:
#Consider two random array A and B, check if they are equal 
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [ ]:
#Make an array immutable (read-only)
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

In [ ]:
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.02800728 0.7651483  0.2873742  0.19071631 0.62427178 0.484151
 0.92417395 0.78317974 0.99900968 0.87337728]
[0.69345918 0.54872748 0.36611133 1.55157005 0.9072916  1.0469159
 0.88615489 0.19334451 0.53517175 0.45433843]


In [ ]:
#Create random vector of size 10 and replace the maximum value by 0 
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.90794502 0.22883501 0.38623999 0.         0.91439677 0.66125651
 0.38516632 0.63252511 0.73929211 0.81687355]


In [3]:
#Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [4]:
#Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [5]:
#Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [7]:
#How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
#How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

18


In [9]:
#Create a structured array representing a position (x,y) and a color (r,g,b) 
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [10]:
#Consider a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.43742986 0.35146485 0.55459037 0.38441213 0.38099188
  0.73506139 0.25198299 0.16666976 0.63578798]
 [0.43742986 0.         0.70121352 0.95642155 0.25055861 0.06580341
  0.79862767 0.51009005 0.51768463 0.38098836]
 [0.35146485 0.70121352 0.         0.27319114 0.52248861 0.63562824
  0.53761401 0.57394569 0.19601568 0.72204975]
 [0.55459037 0.95642155 0.27319114 0.         0.79397541 0.89197889
  0.7309411  0.71359479 0.43874981 0.99399416]
 [0.38441213 0.25055861 0.52248861 0.79397541 0.         0.19810339
  0.5492466  0.57053946 0.37687559 0.25158178]
 [0.38099188 0.06580341 0.63562824 0.89197889 0.19810339 0.
  0.74707422 0.47873887 0.45326232 0.36726607]
 [0.73506139 0.79862767 0.53761401 0.7309411  0.5492466  0.74707422
  0.         0.98564425 0.59304372 0.53993974]
 [0.25198299 0.51009005 0.57394569 0.71359479 0.57053946 0.47873887
  0.98564425 0.         0.41195205 0.81361197]
 [0.16666976 0.51768463 0.19601568 0.43874981 0.37687559 0.45326232
  0.59304372 0.41195

In [11]:
#How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[98  1 31 97  3 57 61 31 48 44]


In [12]:
#How to read the file


from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  # Remove the CWD from sys.path while we load stuff.


In [13]:
#What is the equivalent of enumerate for numpy arrays
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [14]:
#Generate a generic 2D Gaussian-like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [15]:
#How to randomly place p elements in a 2D array?

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
#Subtract the mean of each row of a matrix
X = np.random.rand(5, 5)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.35316522  0.24316868 -0.21465014  0.1282175  -0.50990126]
 [-0.12913919  0.09692194  0.50045475 -0.32723507 -0.14100242]
 [ 0.15299738 -0.43084067  0.06511348  0.06203521  0.1506946 ]
 [ 0.06654026  0.35820493 -0.24959619 -0.23524261  0.06009361]
 [ 0.01083477 -0.13720698  0.06078678 -0.19534915  0.26093458]]


In [19]:
#How to sort an array by the nth column?
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 4 2]
 [1 0 1]
 [9 5 8]]
[[1 0 1]
 [8 4 2]
 [9 5 8]]


In [20]:
#How to tell if a given 2D array has null columns?
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [21]:
# Find the nearest value from a given value in an array 
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4182555523110887


In [22]:
#Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [23]:
#Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [24]:
#Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 5. 1. 4. 3. 2. 2. 7. 1. 2.]


In [25]:
#How to accumulate elements of a vector (X) to an array (F) based on an index list (I)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [26]:
#Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [27]:
#Considering a four dimensions array, how to get sum over the last two axis at once
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[37 47 59 53]
 [47 62 50 59]
 [60 57 66 37]]
[[37 47 59 53]
 [47 62 50 59]
 [60 57 66 37]]


In [28]:
#Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.55341802 0.39949054 0.61785343 0.58836243 0.50752825 0.53149613
 0.58824156 0.56875991 0.56434183 0.51940739]


In [29]:
#How to get the diagonal of a dot product?
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([2.32701133, 1.25417787, 1.10928794, 0.77087688, 2.3732056 ])

In [30]:
#Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [31]:
#Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [32]:
#How to swap two rows of an array
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [33]:
#Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2,  9) ( 2, 42) ( 6, 29) ( 6, 67) ( 8, 34) ( 8, 91) ( 9, 42) (15, 56)
 (15, 74) (15, 77) (15, 83) (26, 31) (26, 41) (29, 67) (31, 41) (32, 44)
 (32, 80) (34, 59) (34, 91) (34, 94) (44, 80) (53, 89) (53, 92) (56, 83)
 (59, 94) (73, 74) (73, 90) (74, 77) (74, 90) (89, 92)]


In [34]:
#Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [35]:
#How to compute averages using a sliding window over an array
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [36]:
#Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#How to negate a boolean, or to change the sign of a float inplace
Z = np.random.randint(0,2,10)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,10)
np.negative(Z, out=Z)

array([ 0.34058518, -0.5745786 , -0.2387156 , -0.84732227,  0.0079275 ,
       -0.0847094 , -0.11890598,  0.13966231, -0.99258631,  0.67364979])

In [41]:
#Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.0627806   6.10201816  9.47716104  5.81741332 12.33941628  2.03829178
  7.34934966  3.93991337  1.23003357  0.46637132]


In [42]:
#Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.93183804 16.12179679  8.99497744  0.44787357  9.84764892 10.69259853
   9.73324902  2.19703541  5.78675453  5.70689198]
 [ 2.72669705 13.27722131  3.3176391   5.98446946  6.17187002  8.04804846
  12.4441453   3.1219357  10.94852742  8.58649862]
 [ 4.53127016  5.10985388  7.11984186 16.600128    3.06885179  0.15824879
  13.88877837 10.96970399 18.29629978 10.38513964]
 [ 3.50585966  8.73557105 11.4140388   0.6324249   4.14660925  2.95723924
   1.78039523 10.11468921  2.68146101  5.75031826]
 [ 2.67284213  9.42537374 10.9032448   0.27494918  4.61522825  3.69406543
   0.39714796  9.01454782  1.52753885  4.36600602]
 [ 2.30972025 12.59557517  1.25195927  7.94638909  5.13309572  7.45002593
  13.85617644  5.28946245 13.08423582 10.05464119]
 [ 6.13712471 16.8285261   6.24522899  2.81943943  9.82911881 11.56018558
  13.55744462  1.74917446  9.80653711  9.58169197]
 [ 9.19645327  0.38612535 10.19862014 20.07570301  7.75089386  4.55464525
  11.5264819  11.76331291 18.7761867   8.16180857]


In [43]:
#Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 1 1 8 6 2 0 3 5 8]
 [2 1 8 6 3 4 5 8 2 3]
 [8 6 1 8 6 0 6 8 5 8]
 [2 3 6 2 7 0 0 5 8 5]
 [7 4 0 0 7 5 3 6 9 3]
 [0 4 6 3 4 8 4 6 0 7]
 [6 9 3 7 6 2 4 9 0 8]
 [0 1 2 7 0 5 5 0 8 7]
 [1 3 9 2 0 5 8 5 5 0]
 [2 0 9 1 9 1 5 1 5 6]]
[[0 0 0 0 0]
 [0 4 1 1 8]
 [0 2 1 8 6]
 [0 8 6 1 8]
 [0 2 3 6 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [44]:
#Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [45]:
#Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [46]:
#How to find the most frequent value in an array
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [49]:
#Extract all the contiguous 3x3 blocks from a random 10x10 matrix 
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 0]
   [1 1 3]
   [0 4 3]]

  [[2 0 1]
   [1 3 2]
   [4 3 2]]

  [[0 1 4]
   [3 2 0]
   [3 2 1]]

  [[1 4 4]
   [2 0 4]
   [2 1 4]]

  [[4 4 4]
   [0 4 0]
   [1 4 3]]

  [[4 4 4]
   [4 0 3]
   [4 3 1]]

  [[4 4 1]
   [0 3 0]
   [3 1 4]]

  [[4 1 4]
   [3 0 1]
   [1 4 4]]]


 [[[1 1 3]
   [0 4 3]
   [4 0 2]]

  [[1 3 2]
   [4 3 2]
   [0 2 2]]

  [[3 2 0]
   [3 2 1]
   [2 2 1]]

  [[2 0 4]
   [2 1 4]
   [2 1 1]]

  [[0 4 0]
   [1 4 3]
   [1 1 0]]

  [[4 0 3]
   [4 3 1]
   [1 0 4]]

  [[0 3 0]
   [3 1 4]
   [0 4 1]]

  [[3 0 1]
   [1 4 4]
   [4 1 0]]]


 [[[0 4 3]
   [4 0 2]
   [4 2 4]]

  [[4 3 2]
   [0 2 2]
   [2 4 0]]

  [[3 2 1]
   [2 2 1]
   [4 0 2]]

  [[2 1 4]
   [2 1 1]
   [0 2 1]]

  [[1 4 3]
   [1 1 0]
   [2 1 1]]

  [[4 3 1]
   [1 0 4]
   [1 1 4]]

  [[3 1 4]
   [0 4 1]
   [1 4 1]]

  [[1 4 4]
   [4 1 0]
   [4 1 4]]]


 [[[4 0 2]
   [4 2 4]
   [4 0 2]]

  [[0 2 2]
   [2 4 0]
   [0 2 0]]

  [[2 2 1]
   [4 0 2]
   [2 0 2]]

  [[2 1 1]
   [0 2 1]
   [0 2 1]]

  [[1 1 0]
   

In [50]:
#Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6 10  7  5 10]
 [10  5  0 11  9]
 [ 7  0  5 42  6]
 [ 5 11 42  5  8]
 [10  9  6  8  6]]


In [51]:
#Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [52]:
#Consider a 16x16 array, how to get the block-sum (block size is 4x4)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [53]:
#How to implement the Game of Life using numpy arrays
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [54]:
#How to get the n largest values of an array
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


In [55]:
#Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [56]:
#How to create a record array from a regular array
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [57]:
#Consider a large vector Z, compute Z to the power of 3 using 3 different methods
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.81 s ± 195 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
140 ms ± 769 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
118 ms ± 612 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [58]:
#Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 5 7]


In [59]:
#Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 1 4]
 [2 1 4]
 [1 1 0]
 [0 2 4]
 [2 0 2]
 [2 3 1]
 [1 2 2]
 [0 4 0]
 [0 3 1]
 [3 0 4]]
[[2 1 4]
 [2 1 4]
 [1 1 0]
 [0 2 4]
 [2 0 2]
 [2 3 1]
 [1 2 2]
 [0 4 0]
 [0 3 1]
 [3 0 4]]
[[2 1 4]
 [2 1 4]
 [1 1 0]
 [0 2 4]
 [2 0 2]
 [2 3 1]
 [1 2 2]
 [0 4 0]
 [0 3 1]
 [3 0 4]]


In [60]:
#Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [61]:
#Given a two dimensional array, how to extract unique rows
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [62]:
#Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    

array([[0.00307835, 0.05860391, 0.1211555 , 0.06468711, 0.05457079,
        0.07904899, 0.07849581, 0.01971464, 0.06481543, 0.02361062],
       [0.01049921, 0.19987801, 0.41322021, 0.22062574, 0.18612241,
        0.26960921, 0.26772251, 0.06723993, 0.22106339, 0.08052779],
       [0.0221034 , 0.42079192, 0.86992927, 0.46447095, 0.39183303,
        0.5675931 , 0.56362113, 0.14155645, 0.46539231, 0.16953062],
       [0.02135213, 0.40648976, 0.84036151, 0.4486842 , 0.37851514,
        0.54830135, 0.54446439, 0.13674513, 0.44957424, 0.1637685 ],
       [0.00365009, 0.06948842, 0.14365774, 0.07670146, 0.06470623,
        0.09373077, 0.09307485, 0.02337624, 0.07685361, 0.02799582],
       [0.02175188, 0.41409987, 0.85609437, 0.45708425, 0.38560152,
        0.55856639, 0.5546576 , 0.13930521, 0.45799096, 0.16683449],
       [0.00994087, 0.1892487 , 0.39124559, 0.20889309, 0.17622461,
        0.25527167, 0.2534853 , 0.06366418, 0.20930747, 0.0762454 ],
       [0.00496049, 0.09443492, 0.1952311

In [63]:
#Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [64]:
#Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [65]:
#Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.26210166  0.08184877]
